# Understanding Transformers with CIFAR100
## Code adapted from https://github.com/phlippe/uvadlc_notebooks/tree/master/docs/tutorial_notebooks/tutorial6

### Boilerplate

In [1]:
## Standard libraries
import os
import numpy as np 
import random
from PIL import Image
from types import SimpleNamespace

## Imports for plotting
import matplotlib.pyplot as plt
%matplotlib inline 
from IPython.display import set_matplotlib_formats
set_matplotlib_formats('svg', 'pdf') # For export
import matplotlib
matplotlib.rcParams['lines.linewidth'] = 2.0
import seaborn as sns
sns.reset_orig()

## PyTorch
import torch
import torch.nn as nn
import torch.utils.data as data
import torch.optim as optim
import pytorch_lightning as pl
# Torchvision
import torchvision
from torchvision.datasets import CIFAR100
from torchvision import transforms

/var/folders/2v/0s_wd0cd04g3xtcdpppg90980000gn/T/ipykernel_3057/3910507964.py:12: DeprecationWarning: `set_matplotlib_formats` is deprecated since IPython 7.23, directly use `matplotlib_inline.backend_inline.set_matplotlib_formats()`
  set_matplotlib_formats('svg', 'pdf') # For export


In [2]:
device = torch.device("mps") if torch.mps.is_available() else torch.device("cpu")
print("Using device", device)

Using device mps


In [3]:
DATASET_PATH = "../data"
CHECKPOINT_PATH = "./saved_models"
pl.seed_everything(42)

Seed set to 42


42

In [4]:
import urllib.request
from urllib.error import HTTPError
# Github URL where saved models are stored for this tutorial
base_url = "https://raw.githubusercontent.com/phlippe/saved_models/main/tutorial6/"
# Files to download
pretrained_files = ["SetAnomalyTask.ckpt"]

# Create checkpoint path if it doesn't exist yet
os.makedirs(CHECKPOINT_PATH, exist_ok=True)

# For each file, check whether it already exists. If not, try downloading it.
for file_name in pretrained_files:
    file_path = os.path.join(CHECKPOINT_PATH, file_name)
    if "/" in file_name:
        os.makedirs(file_path.rsplit("/",1)[0], exist_ok=True)
    if not os.path.isfile(file_path):
        file_url = base_url + file_name
        print(f"Downloading {file_url}...")
        try:
            urllib.request.urlretrieve(file_url, file_path)
        except HTTPError as e:
            print("Something went wrong. Please try to download the file from the GDrive folder, or contact the author with the full output including the following error:\n", e)

### Attention

In [48]:
m = nn.Softmax(dim=1)
input = torch.tensor([1,3,5], dtype = float).view(1,-1)
output = m(input)
output2 = m(input/5)
print(output, output2)

tensor([[0.0159, 0.1173, 0.8668]], dtype=torch.float64) tensor([[0.2120, 0.3162, 0.4718]], dtype=torch.float64)


In [44]:
input

tensor([[1., 3., 5.]], dtype=torch.float64)

In [46]:
output

tensor([[0.0159, 0.1173, 0.8668]], dtype=torch.float64)

In [34]:
np.exp(1)/(np.exp(1) + np.exp(3) + np.exp(5))

0.015876239976466765

### Exercises